# Generated by Django 4.2.7 on 2023-11-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('periodity', models.DateField(blank=True, default=None, null=True, verbose_name='periodicity')),
                ('pdf', models.FileField(upload_to='instructions')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='orimgasapp.company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orimgasapp.company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='PositionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ManyToManyField(related_name='position_instruction', to='orimgasapp.instruction', verbose_name='instruction')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_instruction', to='orimgasapp.position', verbose_name='position')),
            ],
        ),
    ]
