# Generated by Django 4.2.7 on 2023-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0002_userinstructionsign_delete_positioninstruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='periodity',
        ),
        migrations.AddField(
            model_name='instruction',
            name='periodiskumas',
            field=models.IntegerField(blank=True, null=True, verbose_name='periodicity'),
        ),
    ]
