# Generated by Django 5.0.2 on 2024-03-14 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0006_alter_instruction_periodiskumas_kitidokumentai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='testas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='orimgasapp.testai', verbose_name='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priesgiasrinesinstrukcijos',
            name='instruktavimo_tipas',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pirminis'), (1, 'Periodinis')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='kitudocpasirasymas',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nepasirašyta'), (1, 'Pasirašyta')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='mokymupasirasymas',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nepasirašyta'), (1, 'Pasirašyta')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='priesgaisriniupasirasymas',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nepasirašyta'), (1, 'Pasirašyta')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userinstructionsign',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nepasirašyta'), (1, 'Pasirašyta')], default=0, verbose_name='status'),
        ),
    ]
