# Generated by Django 5.0.2 on 2024-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0007_instruction_testas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priesgiasrinesinstrukcijos',
            name='instruktavimo_tipas',
        ),
        migrations.AddField(
            model_name='priesgaisriniupasirasymas',
            name='instruktavimo_tipas',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pirminis'), (1, 'Periodinis')], default=0, verbose_name='status'),
        ),
    ]
