# Generated by Django 5.0.2 on 2024-03-18 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0010_remove_mokymai_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mokymai',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
