# Generated by Django 5.0.2 on 2024-03-26 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0012_kitudocpasirasymas_uuid_mokymupasirasymas_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilineSauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('periodiskumas', models.IntegerField(blank=True, default=365, null=True, verbose_name='periodicity')),
                ('pdf', models.FileField(upload_to='civiline_sauga')),
                ('imone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civiline_sauga', to='orimgasapp.company', verbose_name='company')),
                ('testas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civiline_sauga', to='orimgasapp.testai', verbose_name='test')),
            ],
        ),
        migrations.CreateModel(
            name='CivilineSaugaPasirasymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Nepasirašyta'), (1, 'Pasirašyta')], default=0, verbose_name='status')),
                ('date_signed', models.DateField(blank=True, default=None, null=True, verbose_name='date signed')),
                ('next_sign', models.DateField(blank=True, default=None, null=True, verbose_name='next sign')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orimgasapp.civilinesauga', verbose_name='instruction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
