# Generated by Django 5.0.2 on 2024-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0013_civilinesauga_civilinesaugapasirasymas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priesgaisriniupasirasymas',
            name='instruktavimo_tipas',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Įvadinis'), (1, 'Periodinis')], default=0, verbose_name='status'),
        ),
    ]
