# Generated by Django 5.0.2 on 2024-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0014_alter_priesgaisriniupasirasymas_instruktavimo_tipas'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilinesaugapasirasymas',
            name='instruktavimo_tipas',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Įvadinis'), (1, 'Periodinis')], default=0, verbose_name='status'),
        ),
    ]
