# Generated by Django 5.0.2 on 2024-03-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0015_civilinesaugapasirasymas_instruktavimo_tipas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstructionsign',
            name='instruktavimo_tipas',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Įvadinis'), (1, 'Periodinis')], default=0, verbose_name='status'),
        ),
    ]
