# Generated by Django 5.0.2 on 2024-03-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0016_userinstructionsign_instruktavimo_tipas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilinesauga',
            name='testas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='civiline_sauga', to='orimgasapp.testai', verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='testas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='orimgasapp.testai', verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='mokymai',
            name='testas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mokymai', to='orimgasapp.testai', verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='priesgiasrinesinstrukcijos',
            name='testas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priesgiasrines_instrukcijos', to='orimgasapp.testai', verbose_name='test'),
        ),
    ]
