# Generated by Django 5.0.2 on 2024-09-03 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0018_civilinesauga_uuid_instruction_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsmeninesApsaugosPriemones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=9999, verbose_name='pavadinimas')),
                ('periodiskumas', models.SmallIntegerField(choices=[(6, '6 mėnesiai'), (12, '12 mėnesių'), (24, '24 mėnesiai'), (36, '36 mėnesiai')], default=6, verbose_name='periodicity')),
            ],
        ),
        migrations.AlterField(
            model_name='civilinesauga',
            name='pavadinimas',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.CharField(max_length=9999, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='kitidokumentai',
            name='pavadinimas',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='mokymai',
            name='pavadinimas',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='priesgiasrinesinstrukcijos',
            name='pavadinimas',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='testai',
            name='pavadinimas',
            field=models.CharField(max_length=9999, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='testoatsakymas',
            name='atsakymas',
            field=models.CharField(max_length=9999, verbose_name='atsakymas'),
        ),
        migrations.AlterField(
            model_name='testoklausimas',
            name='klausimas',
            field=models.CharField(max_length=9999, verbose_name='klausimas'),
        ),
        migrations.CreateModel(
            name='AAPPasirasymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Nepasirašyta'), (1, 'Pasirašyta')], default=0, verbose_name='status')),
                ('date_signed', models.DateField(blank=True, default=None, null=True, verbose_name='date signed')),
                ('next_sign', models.DateField(blank=True, default=None, null=True, verbose_name='next sign')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('AAP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orimgasapp.asmeninesapsaugospriemones', verbose_name='instruction')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='AAP',
            field=models.ManyToManyField(blank=True, default=None, related_name='AAP', to='orimgasapp.asmeninesapsaugospriemones'),
        ),
    ]
