# Generated by Django 5.0.2 on 2024-09-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0019_asmeninesapsaugospriemones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asmeninesapsaugospriemones',
            name='mato_vnt',
            field=models.SmallIntegerField(choices=[(1, 'Vnt.'), (2, 'Pora'), (3, 'Kompl.')], default=1, verbose_name='mato vnt.'),
        ),
        migrations.AddField(
            model_name='asmeninesapsaugospriemones',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='aap_priemones', verbose_name='pdf'),
        ),
    ]
