# Generated by Django 4.2.7 on 2024-09-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0020_asmeninesapsaugospriemones_mato_vnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asmeninesapsaugospriemones',
            name='pavadinimas',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='civilinesauga',
            name='pavadinimas',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.CharField(max_length=10000, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='kitidokumentai',
            name='pavadinimas',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='mokymai',
            name='pavadinimas',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='priesgiasrinesinstrukcijos',
            name='pavadinimas',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='testai',
            name='pavadinimas',
            field=models.CharField(max_length=10000, verbose_name='pavadinimas'),
        ),
        migrations.AlterField(
            model_name='testoatsakymas',
            name='atsakymas',
            field=models.CharField(max_length=10000, verbose_name='atsakymas'),
        ),
        migrations.AlterField(
            model_name='testoklausimas',
            name='klausimas',
            field=models.CharField(max_length=10000, verbose_name='klausimas'),
        ),
    ]
