# Generated by Django 5.0.2 on 2025-01-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0022_skyrius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='skyrius',
        ),
        migrations.AddField(
            model_name='skyrius',
            name='company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skyrius', to='orimgasapp.company'),
        ),
    ]
