# Generated by Django 5.0.2 on 2025-04-15 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0023_remove_company_skyrius_skyrius_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPriminimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=10000, verbose_name='pavadinimas')),
                ('pdf', models.FileField(upload_to='adminpriminimas')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('imone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminpriminimas', to='orimgasapp.company', verbose_name='imone')),
            ],
        ),
    ]
