# Generated by Django 5.0.2 on 2025-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0024_adminpriminimas'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilinesauga',
            name='kalba',
            field=models.SmallIntegerField(choices=[(1, 'LT'), (2, 'RU'), (3, 'EN')], default=1, verbose_name='kalba'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='kalba',
            field=models.SmallIntegerField(choices=[(1, 'LT'), (2, 'RU'), (3, 'EN')], default=1, verbose_name='kalba'),
        ),
        migrations.AddField(
            model_name='kitidokumentai',
            name='kalba',
            field=models.SmallIntegerField(choices=[(1, 'LT'), (2, 'RU'), (3, 'EN')], default=1, verbose_name='kalba'),
        ),
        migrations.AddField(
            model_name='mokymai',
            name='kalba',
            field=models.SmallIntegerField(choices=[(1, 'LT'), (2, 'RU'), (3, 'EN')], default=1, verbose_name='kalba'),
        ),
        migrations.AddField(
            model_name='priesgiasrinesinstrukcijos',
            name='kalba',
            field=models.SmallIntegerField(choices=[(1, 'LT'), (2, 'RU'), (3, 'EN')], default=1, verbose_name='kalba'),
        ),
    ]
