# Generated by Django 4.2.7 on 2026-01-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orimgasapp', '0025_civilinesauga_kalba_instruction_kalba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Personalo_modulis',
            field=models.BooleanField(default=False, verbose_name='Personalo modulis'),
        ),
    ]
