# Generated by Django 5.0.2 on 2024-03-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_photo_user_date_of_birth'),
        ('orimgasapp', '0006_alter_instruction_periodiskumas_kitidokumentai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kiti_dokumentai',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='orimgasapp.kitidokumentai', verbose_name='kiti dokumentai'),
        ),
        migrations.AddField(
            model_name='user',
            name='med_patikros_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='med_patikros_periodas',
            field=models.SmallIntegerField(choices=[(12, '12 Mėnesių'), (24, '24 Mėnesių')], default=12, verbose_name='med patikros periodas'),
        ),
        migrations.AddField(
            model_name='user',
            name='mokymai',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='orimgasapp.mokymai', verbose_name='mokymai'),
        ),
        migrations.AddField(
            model_name='user',
            name='priesgaisrines',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='orimgasapp.priesgiasrinesinstrukcijos', verbose_name='PriesgiasrinesInstrukcijos'),
        ),
        migrations.AddField(
            model_name='user',
            name='sekanti_med_patikros_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
