# Generated by Django 5.0.2 on 2024-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_uuid'),
        ('orimgasapp', '0013_civilinesauga_civilinesaugapasirasymas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='civiline_sauga',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to='orimgasapp.civilinesauga', verbose_name='CivilineSauga'),
        ),
    ]
